services:
  - type: web
    name: turkistan-invest
    env: docker
    plan: free
    region: frankfurt
    branch: main
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: Turkistan Invest
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: turkistan-invest-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: turkistan-invest-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: turkistan-invest-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: turkistan-invest-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: turkistan-invest-db
          property: password

databases:
  - name: turkistan-invest-db
    plan: free
    region: frankfurt
    databaseName: invest
    user: turkistan_invest_user
